

// --- all_Items PMC-T ----------------------------------------------------------
// - All arsenal Items

cgqc_pmct_arsenal_all = [
    // Helmets ----------------------------------
    "rhs_vkpo_cap",
    "rhs_fieldcap_m88_vsr_2",
    "rhs_fieldcap_m88_vsr",
    "rhs_fieldcap_m88_moldovan_ttsko_hot",
    "rhs_fieldcap_m88_moldovan_ttsko_desat",
    "rhs_fieldcap_m88_ttsko",
    "rhs_fieldcap_m88",
    "rhs_fieldcap_early",
    "rhs_ushanka",
    "rhsgref_patrolcap_specter",
    "rhsgref_fieldcap_ttsko_mountain",
    "rhs_fieldcap_digi2",
    "rhs_fieldcap_khk",
    "rhsgref_fieldcap_ttsko_forest",
    "rhs_fieldcap_vsr",
    "rhsgref_hat_m1941cap",
    "rhsgref_hat_m43cap_heer",
    "rhssaf_bandana_smb",
    "rhssaf_bandana_md2camo",
    "rhsusf_bowman_cap",
    "rhssaf_bandana_oakleaf",
    "rhssaf_bandana_oakleaf",
    "rhssaf_bandana_oakleaf",
    "rhssaf_bandana_oakleaf",
    "PO_H_SSh68Helmet_Partizan_2",
    "rhs_tsh4",
	"rhs_tsh4_ess",
	"rhs_tsh4_bala",
	"rhs_tsh4_ess_bala",
	"rhs_fieldcap_digi_des",
    "rhs_altyn",
	"rhs_altyn_bala",
	"rhs_altyn_visordown",
	"rhs_altyn_novisor",
	"rhs_altyn_novisor_bala",
	"rhs_altyn_novisor_ess",
	"rhs_altyn_novisor_ess_bala",
    // Goggled ----------------------------------
    "G_Bandanna_blk",
    "rhssaf_veil_Green",
    "rhs_facewear_6m2_1",
    "DSF_BIS_olive_shemag",
    "G_Bandanna_beast",
    "G_Bandanna_khk",
    "G_Bandanna_oli",
    "G_Bandanna_tan",
    "G_Bandanna_BlueFlame2",
    "G_Bandanna_CandySkull",
    "G_Bandanna_OrangeFlame1",
    "G_Bandanna_Skull1",
    "G_Bandanna_Syndikat1",
    "G_Bandanna_Skull2",
    "G_Bandanna_Vampire_01",
    "G_Bandanna_Syndikat2",
    "G_mas_can_shemag",
    "G_mas_can_shemag_gog_l",
    "G_mas_can_shemag_gog",
    "G_mas_can_shemag_low",
    "G_mas_can_shemag_mask",
    "G_Lowprofile",
    "rhs_scarf",
    "G_Bandanna_Syndikat2",
    // NVG ------------------------------------
    "rhs_1PN138",
    "rhsusf_ANPVS_15",
    // Vests ------------------------------------
    "cgqc_vest_pmct_tan",
    "cgqc_vest_mk1_driver",
    // Uniforms ----------------------------------
    "cgqc_uniform_pmct_cadpat",
    // Rucks ------------------------------------
    "B_AssaultPack_cbr",
    "cgqc_pack_mk1_radiobag_black",
    "B_Kitbag_cbr",
    "B_Carryall_cbr",
    "rhs_rpg_2",
    "B_UAV_01_backpack_F",
    // Handguns ------------------------------------
    "rhs_weap_pya",
    "rhs_weap_tt33",
    "rhs_mag_9x19_7n31_17",
    "rhs_weap_tt33",
    // Primary ------------------------------------
    "cgqc_gun_pmct_ak12",
    "cgqc_gun_pmct_aku12",
    "cgqc_gun_pmct_ak12gl",
    "hlc_30Rnd_545x39_B_AK_Black",
    "hlc_30Rnd_545x39_S_AK_Black",
    "rhs_30Rnd_545x39_7N10_AK",
    "grcb_30Rnd_545x39_7N22_AK_mix",
    "rhs_30Rnd_545x39_7N22_AK",
    "grcb_30Rnd_545x39_7N22_AK_mix",
    "grcb_30Rnd_545x39_7N39_AK",
    "grcb_30Rnd_545x39_7N39_AK_mix",
    "cgqc_gun_pmct_rpk12",
    "grcb_60Rnd_545x39_7N10",
    "grcb_60Rnd_545x39_7N10_mix",
    "grcb_60Rnd_545x39_7N22",
    "grcb_60Rnd_545x39_7N22_mix",
    "grcb_60Rnd_545x39_7N39",
    "grcb_60Rnd_545x39_7N39_mix",
    "cgqc_gun_pmct_mg3",
    "Tier1_250Rnd_762x51_Belt_M80A1_EPR",
    "Tier1_250Rnd_762x51_Belt_M993_AP",
    "Tier1_100Rnd_762x51_Belt_M80A1_EPR",
    "Tier1_100Rnd_762x51_Belt_M993_AP",
    "cgqc_gun_pmct_svd",
    "rhs_10Rnd_762x54mmR_7N14",
    "ACE_10Rnd_762x54_Tracer_mag",
    "cgqc_gun_pmct_AWM",
    "hlc_5rnd_300WM_mk248_AWM",
    "hlc_5rnd_300WM_SBT_AWM",
    "hlc_5rnd_300WM_AP_AWM",
    "cgqc_gun_pmct_svd",
    "hlc_VOG25_AK",
    "hlc_GRD_White",
    "hlc_GRD_Red",
    "hlc_GRD_green",
    // Accessories -----------------------------------------------
    "rhs_acc_dtk3",
    "rhs_acc_2dpZenit_ris",
    "rhs_acc_rakursPM",
    "rhs_acc_1p87",
    "rhs_acc_ekp8_18",
    "rhs_acc_okp7_picatinny",
    "optic_DMS",
    "rhs_acc_dh520x56",
    "rhs_acc_1p87",
    "rhs_acc_1p87",
    "rhs_acc_1p87",

    // Launchers ------------------------------------
    "launch_RPG7_F",
    "rhs_rpg7_PG7V_mag",
    "rhs_weap_rpg26",
    "rhs_weap_rshg2",
    // Throwables ----------------------------------
    "SmokeShell",
    "rhs_mag_rgd5",
    // Explosives ----------------------------------
    "rhssaf_tm500_mag",
    "rhssaf_tm200_mag",
    "rhssaf_tm100_mag",
    // Radios -----------------------------------
    "ACRE_PRC343",
    "ACRE_PRC148",
    "ACRE_PRC152",
    "ACRE_PRC117F",
    // Engineer items ---------------------------
    "ToolKit",
    "ACE_DefusalKit",
    "ACE_M26_Clacker",
    "Rev_demine_item",
    "ACE_VMH3",
    "ACE_VMM3",
    // Meds -----------------------------------
    "ACE_fieldDressing",
    "ACE_splint",
    "ACE_tourniquet",
    "FF_Painkiller",
    "ACE_bodyBag",
    "ACE_epinephrine",
    "ACE_morphine",
    "ACE_adenosine",
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
    "ACE_personalAidKit",
    "FSGm_ItemMedicBag",
    // Logistics  -----------------------------------
    "cgqc_items_ifak",
    "cgqc_items_medkit",
    "cgqc_bandolier_ammo",
    // Items -----------------------------------
    "ACE_EarPlugs",
    "ACE_CableTie",
    "ACE_MapTools",
    "ACE_EntrenchingTool",
    "grad_paceCountBeads_functions_paceCountBeads",
    "ACE_RangeCard",
    "ACE_Canteen",
    "ACE_SpottingScope",
    "ACE_SpraypaintBlack",
    "ACE_SpraypaintBlue",
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_Tripod",
    "ACE_UAVBattery",
    "ACE_wirecutter",
    "acex_intelitems_notepad",
    "KNB_PanelGreen",
	"KNB_PanelRed",
    "KNB_PanelYellow",
    "murshun_cigs_cigpack",
    "murshun_cigs_lighter",
    "immersion_cigs_cigar0_nv",
    // Electronics ------------------------------
    "ItemAndroid",
    "ACE_microDAGR",
    "WBK_HeadLampItem",
    "ACE_Flashlight_KSF1",
    "azm_bft_rx",
    "azm_bft_tx",
    "ACE_ATragMX",
    "ACE_Kestrel4500",
    "NER_item_bulatv3",
	"Item_JammerSania",
	"Item_JammerVolnorez",
    // Drones ------------------------------
    "Rev_darter_item",
    "Rev_pelican_item",
    // Binoculars ------------------------------
    "Binocular",
    "cgqc_item_rangefinder",
    "ACE_Vector",
    "Nikon_DSLR_HUD",
    // Linked items ------------------------------------
    "ItemMap",
    "ItemGPS",
    "ItemCompass",
    "ItemWatch",
    "ACE_Altimeter",
    "ChemicalDetector_01_watch_F",
    "B_UavTerminal"
];