#include "\cgqc\dialogs\Common.hpp"
//#include "\cgqc\dialogs\dia_vic_gui.hpp"
#include "\cgqc\dialogs\defines.hpp"
#include "\cgqc\dialogs\landnav_gui.hpp"
#include "\cgqc\dialogs\combat_gui.hpp"
#include "\cgqc\dialogs\convoy_gui.hpp"
#include "\cgqc\dialogs\renameVic_gui.hpp"
#include "\cgqc\dialogs\splash.hpp"