// --- all_Items SWAT ----------------------------------------------------------
// - All arsenal Items

cgqc_pmct_arsenal_all = [
    // Helmets ----------------------------------
    "cgqc_helmet_mk1_f_black",
    "cgqc_helmet_mk1_f_gray",
    // Goggled ----------------------------------
    "G_mas_can_gasmask",
    "G_AirPurifyingRespirator_02_black_F",
    "G_mas_can_balaM_b",
    "G_mas_can_gog",
    "G_mas_can_mask_b",
    "G_mas_can_wrap_gog_B",
    "G_Lowprofile",
    // NVG ------------------------------------
    "JAS_GPNVG18_blk",
    // Vests ------------------------------------
    "cgqc_vest_mk1_black_lr",
    "cgqc_vest_mk1_black_rf",
    "cgqc_vest_mk1_black_ar",
    "cgqc_vest_mk1_black",
    "cgqc_vest_mk1_cadpat_lr",
    "cgqc_vest_mk1_cadpat_rf",
    "cgqc_vest_mk1_cadpat_ar",
    "cgqc_vest_mk1_cadpat",
    // Uniforms ----------------------------------
    "cgqc_uniform_mk1_black",
    "U_mas_can_B_suite_CQB",
    "U_O_R_Gorka_01_black_F",
    // Rucks ------------------------------------
    "B_LegStrapBag_black_F",
    "cgqc_pack_mk1_assault_black",
    "cgqc_pack_mk1_kitbag_black",
    "cgqc_pack_mk1_carryall_black",
    "cgqc_pack_mk1_radiobag_black",
    // Handguns ------------------------------------
    "rhs_weap_M320",
    "rhs_mag_m4009",
    "UGL_FlareGreen_F",
    "UGL_FlareCIR_F",
    "UGL_FlareWhite_F",
    "ACE_40mm_Flare_white",
    "1Rnd_Smoke_Grenade_shell",
    "1Rnd_SmokeBlue_Grenade_shell",
    "1Rnd_SmokeGreen_Grenade_shell",
    "1Rnd_SmokePurple_Grenade_shell",
    "1Rnd_SmokeRed_Grenade_shell",
    "rhs_mag_M585_white_cluster",
    "ACE_40mm_Flare_ir",
    // Primary ------------------------------------
    "hlc_smg_mp5k_PDW",
    "rhsusf_weap_MP7A2_grip2",
    "cgqc_gun_mk1_p90",
    "hlc_rifle_honeybase",
    "hlc_smg_mp5sd6",
    "hlc_mp510_tac",
    "hlc_smg_mp5N_tac",
    "hlc_smg_9mmar",
    "hlc_rifle_416D10_ptato",
    "hlc_wp_SCAR_PDW_Blk",
    "rhs_weap_m24sws",
    "rhs_weap_m14_socom_rail",
    "hlc_rifle_PSG1A1_RIS",
    "sgun_mas_can_benelli_F",
    // Ammo -------------------------------------------------
    "hlc_30Rnd_9x19_SD_MP5",
    "rhsusf_mag_40Rnd_46x30_AP",
    "50Rnd_570x28_SMG_03",
    "hlc_29rnd_300BLK_STANAG_S",
    "hlc_30Rnd_10mm_JHP_MP5",
    "hlc_30Rnd_9x19_GD_MP5",
    "rhs_mag_m4009",
    "hlc_30rnd_556x45_S_L5",
    "hlc_30rnd_556x45_S_EMAG",
    "hlc_20Rnd_762x51_S_M14",
    "rhsusf_5Rnd_762x51_m118_special_Mag",
    "hlc_20rnd_762x51_S_G3",
    "7Rnd_mas_can_12Gauge_Slug",
    "7Rnd_mas_can_12Gauge_Pellets",
    "training_mag_2rnd_12g_rubber",
    // Optics -----------------------------------------------
    "Tier1_MicroT2_Leap_Black"
    "rhsusf_acc_T1_low",
    "Tier1_MicroT2_Low_Black",
    "Tier1_Shortdot_Geissele_Docter_Black_PIP",
    "rhsusf_acc_LEUPOLDMK4",
    "rhsusf_acc_M8541_low",
    // Laser/Light -----------------------------------------------
    "Tier1_MP7_NGAL_M300C_Black_FL",
    "Tier1_MP7_NGAL_M300C_Black",
    "Tier1_NGAL_Side",
    "Tier1_SCAR_NGAL_M603V_FL",
    // Suppressors -----------------------------------------------
    "rhsusf_acc_rotex_mp7",
    "muzzle_snds_570",
    "hlc_muzzle_556NATO_rotexiiic_tan",
    "Tier1_AAC_M42000_Black",
    "rhsusf_acc_aac_m14dcqd_silencer",
    // Bipods -----------------------------------------------
    "rhsusf_acc_grip2",
    "hlc_grip_SAW_Grip1",
    "rhsusf_acc_m14_bipod",
    "rhsusf_acc_harris_swivel",
    "121_USASOC_Atlas",
    // Launchers ------------------------------------

    // Throwables ----------------------------------
    "B_IR_Grenade",
    "MS_Strobe_Mag_1",
    "MS_Strobe_Mag_2",
    "ACE_Chemlight_HiGreen",
    "Chemlight_green",
    "ACE_Chemlight_HiRed",
    "ACE_Chemlight_IR",
    "ACE_Chemlight_UltraHiOrange",
    "ACE_HandFlare_Green",
    "ACE_HandFlare_White",
    "SmokeShellBlue",
    "SmokeShellGreen",
    "SmokeShellPurple",
    "SmokeShellRed",
    "SmokeShell",
    "ACE_M84",
    "rhs_grenade_mki_mag",
    "rhs_grenade_mkiiia1_mag",
    "rhs_mag_m7a3_cs",
    "SmokeShellBlue",
    // Explosives ----------------------------------
    "tsp_popperCharge_mag",
    "tsp_popperCharge_auto_mag",
    "tsp_stickCharge_mag",
    "tsp_stickCharge_auto_mag",
    "tsp_frameCharge_mag",

    // Radios -----------------------------------
    "ACRE_PRC343",
    "ACRE_PRC148",
    "ACRE_PRC152",
    "ACRE_PRC117F",
    // Engineer items ---------------------------
    "ToolKit",
    "ACE_DefusalKit",
    "ACE_M26_Clacker",
    "Rev_demine_item",
    "ACE_VMH3",
    "ACE_VMM3",
    // Meds -----------------------------------
    "ACE_fieldDressing",
    "ACE_splint",
    "ACE_tourniquet",
    "FF_Painkiller",
    "ACE_bodyBag",
    "ACE_epinephrine",
    "ACE_morphine",
    "ACE_adenosine",
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
    "ACE_personalAidKit",
    "FSGm_ItemMedicBag",
    // Logistics  -----------------------------------
    "cgqc_items_ifak",
    "cgqc_items_medkit",
    "cgqc_bandolier_ammo",
    // Items -----------------------------------
    "ACE_EarPlugs",
    "ACE_CableTie",
    "ACE_MapTools",
    "ACE_RangeCard",
    "ACE_Canteen",
    "ACE_SpottingScope",
    "ACE_SpraypaintBlack",
    "ACE_SpraypaintBlue",
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_Tripod",
    "ACE_UAVBattery",
    "ACE_wirecutter",
    "acex_intelitems_notepad",
    "KNB_PanelGreen",
	"KNB_PanelRed",
    "KNB_PanelYellow",
    "murshun_cigs_cigpack",
    "murshun_cigs_lighter",
    "immersion_cigs_cigar0_nv",
    // Electronics ------------------------------
    "ItemAndroid",
    "ACE_microDAGR",
    "WBK_HeadLampItem",
    "azm_bft_rx",
    "azm_bft_tx",
    "ACE_ATragMX",
    "ACE_Kestrel4500",
    // Drones ------------------------------

    // Binoculars ------------------------------
    "Binocular",
    "cgqc_item_rangefinder",
    "ACE_Vector",
    "Nikon_DSLR_HUD",
    // Linked items ------------------------------------
    "ItemMap",
    "ItemGPS",
    "ItemCompass",
    "ItemWatch",
    "ACE_Altimeter",
    "ChemicalDetector_01_watch_F",
    "B_UavTerminal"
];