#define PREFIX CGQC
#define MAJOR 4
#define MINOR 10
#define PATCH 4
#define BUILD 0
#define VERSION MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define REQUIRED_VERSION 1.88


#define DEBUG_MODE_FULL
//#define DEBUG_MODE_NORMAL