#define PREFIX CGQC
#define MAJOR 4
#define MINOR 6
#define PATCH 14
#define BUILD 3
#define VERSION MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define REQUIRED_VERSION 1.88


#define DEBUG_MODE_FULL
//#define DEBUG_MODE_NORMAL