// Rang 4 - Sgt - Recon/Centaure
cgqc_mk2_arsenal_rank4 = [
    // Radios -----------------------------------
    "ACRE_PRC152",
    // Uniforms -----------------------------------
    "cgqc_uniform_mk1_diver",
    // Vests -----------------------------------
    "cgqc_vest_mk1_diver",
    // goggles -----------------------------------
    "cgqc_goggles_mk1_diver",
    // Backpacks -----------------------------------
    "B_SCBA_01_F",
    "cgqc_pack_mk1_Radiobag",
    "cgqc_pack_mk1_Radiobag_desert",
    "cgqc_pack_mk1_Radiobag_mcam",
    "cgqc_pack_mk1_Radiobag_cadpat",
    "cgqc_pack_mk1_Radiobag_black",
    "cgqc_pack_mk1_Radiobag_white",
    // Items -----------------------------------
    "cigs_matches",
    "cigs_lighter",
    "cigs_lighter",
    "cigs_black_devil_cigpack",
    "cigs_craven_cigpack",
    "cigs_eckstein_cigpack",
    "cigs_lucky_strike_cigpack",
    "cigs_morley_cigpack",
    "cigs_baja_blast_cigpack",
    "cigs_crayons_crayonpack",
    // Electronics ------------------------------
    "ItemcTab",
    "NER_item_bulatv3",
	"Item_JammerSania",
	"Item_JammerVolnorez",
    // Drones ------------------------------
    "Rev_darter",
    "Rev_pelican_item",
    // Linked items ------------------------------------
    "B_UavTerminal",
    // Binoculars ------------------------------
    "Laserdesignator_01_khk_F",
    "Laserdesignator_01_khk_F",
    "Laserdesignator_03",
    "Laserdesignator",
    // NVG ------------------------------
    "JAS_GPNVG18_Full_blk_TI",
    "JAS_GPNVG18_Full_tan_TI",
    // Helmets -----------------------------------
    "cgqc_beret_gray",
    // Scopes -----------------------------------
    "optic_Nightstalker",
    "sn_ns",
    "optic_tws",
    "optic_tws_mg",
    "NForce_Atcr_RMR_Top_SkeetIR_Down",
    "SkeetIR_TWS",
    "SkeetIR_TWS_pip",
    "EoTech_EXPS3_SkeetIR_Down",
    "EoTech_EXPS3_G33_Down_SkeetIR_Down",
    "Elcan_SpecterDR_SkeetIR_Down",
    "Aimpoint_T2_SkeetIR_Down",
    // Sniper ------------------------------------
    "cgqc_gun_mk1_m200",
    "cgqc_gun_mk1_m200_arid",
    "cgqc_gun_mk1_m200_semiarid",
    "cgqc_gun_mk1_m200_tropical",
    "cgqc_gun_mk1_m200_sand",
    "rhs_weap_XM2010",
    "rhs_weap_XM2010_wd",
    "rhs_weap_XM2010_d",
    "rhs_weap_XM2010_sa",
    "srifle_DMR_02_F",
    "srifle_DMR_02_camo_F",
    "srifle_DMR_02_sniper_F",

    // 121 sniper rifles --------------------------------
    "121_USASOC_MRAD",
    "121_USASOC_CTSR",
    "121_USASOC_M2010",
    "121_USASOC_CSR_16",
    "121_USASOC_CSR_24",
    "121_USASOC_PVPS",
    "121_USASOC_RVPS",
    "121_USASOC_RVPS_ANPVS30",
    "121_USASOC_PVPS_ANPVS30",
    "121_USASOC_STORM_SLX_Laser",
    "121_USASOC_Raptar_Laser",
    "121_USASOC_AAC_BLK",
    "121_USASOC_AAC_TAN",
    "121_USASOC_AML338_TAN",
    "121_USASOC_SFMB338",
    "121_USASOC_SOCOM338_BLK",
    "121_USASOC_SOCOM338_MANTA",
    "121_USASOC_SOCOM338_TAN",
    "121_USASOC_Atlas",
    "121_USASOC_Harris",
    "121_338_250gr_API526_10rnd",
    "121_308_Mk316_Mod_0_10rnd",
    "121_300WM_Mk248_Mod_1_10rnd",
    "121_300WM_Berger_OTM_10rnd",
    "121_338_250gr_API526_5rnd",
    "121_300WM_Mk248_Mod_1_5rnd",
    "121_308_M118LR_10rnd",
    "121_338_300gr_NM_10rnd",
    "121_300WM_Mk248_Mod_0_5rnd",
    "121_338_300gr_HPBT_5rnd",
    "121_300WM_Mk248_Mod_0_10rnd",
    "121_308_Mk319_Mod_0_10rnd",
    "121_338_300gr_HPBT_10rnd",
    "121_300WM_Berger_OTM_5rnd",

    // --- Ammo
    "7Rnd_mas_can_408_Mag",
    "7Rnd_mas_can_408_APDS_Mag",
    "rhsusf_5Rnd_300winmag_xm2010",
    "ACE_20Rnd_762x67_Berger_Hybrid_OTM_Mag",
    "ACE_10Rnd_338_300gr_HPBT_Mag",
    // Mortar items -----------------------------------
    "ACE_RangeTable_82mm",
    "ACE_artilleryTable",
    // Mortars ---------------------------------------
    "ace_csw_staticMortarCarry",
    "avm224_W_M224_mortar_carry",
    "ace_csw_carryMortarBaseplate",
    // Mortar ammo ---------------------------------------------------------------------
    "avm224_M_6Rnd_60mm_HE_csw",
    "avm224_M_6Rnd_60mm_HE_0_csw",
    "avm224_M_6Rnd_60mm_SMOKE_csw",
    "avm224_M_6Rnd_60mm_ILLUM_csw",
    "avm224_M_6Rnd_60mm_ILLUM_IR_csw",
    "ACE_1Rnd_82mm_Mo_HE",
    "ACE_1Rnd_82mm_Mo_Illum",
    "ACE_1Rnd_82mm_Mo_Smoke"
];